### ISSUE TITLE
can't create more project (8.14.0

### ISSUE THREAD

**Issue by CasparChou** [sameersbn/docker-gitlab#1035]
I can't create more project in my account
`cat VERSION` 8.14.0

Error message from gitlab I got:
![Error message](http://i.imgur.com/uOaECKy.png)

but the setting at gitlab.yml file has already setted to 0
`default_projects_limit: 0`
and also UI version settings 

how to deal with this problem ? :(

**Comment by r2evans** [comment]
I suspect that setting is the default value given to users when their account is created. For users that already exist, can you:

1. Go to the *Admin Page &gg; Overview &gg; Users*, then select the specific user.
2. Confirm that **Personal projects limit** lists something other than "0".
3. Click on *Edit* (top-right corner of the page) and change the *Access &gg; Projects limit* to something else.

I believe this is a GitLab issue and therefore not specific to this docker image. It is being discussed in https://gitlab.com/gitlab-org/gitlab-ce/issues/17642 (still open) and https://gitlab.com/gitlab-org/gitlab-ce/issues/1129 (closed) at a minimum, though I don't know that any mitigation has been incorporated into CE.

**Comment by r2evans** [comment]
I just tested again on my image (8.15.1), and when I change a user's "Projects limit" to a lower number, they are no longer able to create a new project; when I subsequently change to a higher number, they can again create a new project. So, I guess this is not reproducible with the current version, 8.15.1; I'm not sure if it's a GitLab-8.14 thing or not.

BTW: there are numerous security holes/bugs fixed in [8.14.1](https://about.gitlab.com/2016/11/28/gitlab-8-14-1-released/), [8.14.3](https://about.gitlab.com/2016/12/05/cve-2016-9469/), [8.14.4](https://about.gitlab.com/2016/12/08/gitlab-8-dot-14-dot-4-released/), and [8.14.5](https://about.gitlab.com/2016/12/14/gitlab-8-dot-14-dot-5-released/). ([8.14.2](https://about.gitlab.com/2016/12/01/gitlab-8-dot-14-dot-2-released/) appears to be mostly regression fixes). Even if you choose to stay on the 8.14 chain, I urge you to update to 8.14.5.

**Comment by CasparChou** [comment]
It looks like update GitLab is the last way I can solve this problem...

Very helpful ! Thank you

**Comment by CasparChou** [comment]
Okay , this is weird
I already update GitLab to latest version , but settings still can't  change 
Here is my version list
![](http://i.imgur.com/3Np9ZYB.jpg)

Is there any possible environmental variables which I set when docker run cause this issue ?

**Comment by CasparChou** [comment]
Something new, I can change other user's limit but not my  !!
I feel sad now...

**Comment by r2evans** [comment]
I have no env-vars defined that would change any of that behavior. I was able to change my own (which is how I verified the below-limit behavior), so there is something else going on with you. If it matters, I'm authenticating against an LDAP/AD domain; I don't know if or how that could affect this behavior, but it's the only thing I can think of that may be different between our setups.

**Comment by CasparChou** [comment]
Okay.... The worst but should work way is delete the user and recreate it again
Thank you !

**Comment by chraibi** [comment]
Delete the user? No way!
