### ISSUE TITLE
Container registry backups

### ISSUE THREAD

**Issue by adamlc** [sameersbn/docker-gitlab#1050]
Hey guys, I've just managed to get the container registry up and running. I DONT want containers backed up as they take up a lot of space and can be rebuilt easily if something happens.

From reading the documentation it seems that I can change ```GITLAB_REGISTRY_DIR``` to a different location outside the ```$GITLAB_SHARED_DIR``` and it won't be backed up? Or is there something else I need to do? This might be a common use case for people as it will make HUGE backups if they're all included. It might be worth clarifying in the docs if thats the case.

Thanks!

**Comment by solidnerd** [comment]
Hey,

It depends which storage backend do you use with the registry. You need only to skip the registry backup if you use the local storage otherwise gitlab can't do backups of your registry for you. 

You don't need to change any dir. What you need to do is that skip some parts of the backup process. This can be done by:

```bash
docker-compose run --rm gitlab app:rake gitlab:backup:create SKIP="registry"
```

For more information what you can skip have a look at this:
https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/raketasks/backup_restore.md

**Comment by adamlc** [comment]
Thanks for the help @solidnerd, I should have said I'm using the local storage. I'm also using automated backups, is the skip option something I can add? Thanks!

If not I can quite easily setup a cron to do backups automatically :)

**Comment by adamlc** [comment]
Ignore that, clearly I can't read, just found ```GITLAB_BACKUP_SKIP```, doh!
