### ISSUE TITLE
Insufficient permission for adding an object to repository database

### ISSUE THREAD

**Issue by Lorodion** [sameersbn/docker-gitlab#1161]
Hello,

Recently I have had problems pushing to any GitLab repo (new or old). I even tried setting up a new GitLab instance but always get the same error:

```
Admin@Comp MINGW64 /c/Git/Test (master)
$ git push origin master
Counting objects: 3, done.
Writing objects: 100% (3/3), 214 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
remote: error: insufficient permission for adding an object to repository database /home/git/data/repositories/user/Test.git/./objects/incoming-TKaaPh
remote: fatal: failed to write object
error: unpack failed: unpack-objects abnormal exit
To https://HOST:PORT/user/Test.git
 ! [remote rejected] master -> master (unpacker error)
error: failed to push some refs to 'https://HOST:PORT/user/Test.git'
```

My instance is running on Synology DSM 6 Docker. Sameersbn GitLab is version 9.0.0.
I have tried setting the permissions for the repositories folder to 777 and changing owner to root and git.
So far nothing has helped. Any suggestions?

**Comment by Lorodion** [comment]
Found another way to change permissions for the folders via DSM. Not the ideal solution but it is working for now.

**Comment by tanzeelkazi** [comment]
@Lorodion I am facing the exact same issue as you (Synology DSM 6 Docker with sameersbn:gitlab-9.0.5). Could you tell me how you resolved this issue since applying any sort of permissions from the terminal does not seem to help?

**Comment by tanzeelkazi** [comment]
For now I have update the USERMAP_UID and USERMAP_GID to 0. That's `root` but for my purposes it seems to be working fine.

**Comment by tanzeelkazi** [comment]
So having to set up gitlab to write to my mapped volume as `root` irked me so much that I set up and destroyed around 10 "test" gitlab docker containers on my synology to get to the _root_ of the problem. It is after spending a whole day of docker gitlab instances, that I realized the `git` process within the container was choking on my mapped `data` volume since it had encryption turned on. Turned off encryption, set the `USERMAP_UID` and `USERMAP_GID` to be the same as the `UID` and `GID` assigned by docker (to the container volumes), and now it works like a charm.

In my case `Insufficient permissions...` didn't paint the real picture right away. Hope this helps somebody else running docker-gitlab under a Synology NAS.

P.S: Maybe giving elevated privileges to the docker container could have fixed my problem, but I did NOT try it. Why? Even though it _might_ have worked, I didn't feel it was a good security practice just like setting the `UID` and `GID` to `root` which I had done earlier.

**Comment by Lorodion** [comment]
To elaborate on how I fixed the permissions, it was by setting them via DSM File Station first to 777 and then restrict via SSH inside Docker to the git user. For some reason it was not enough to change the permissions just via SSH, or I was doing something wrong.
My Docker data is also encrypted in DSM, maybe this is part of the problem...

**Comment by tanzeelkazi** [comment]
> For some reason it was not enough to change the permissions just via SSH

That makes sense since setting `chmod 777` on the docker data folder via SSH was not working for me as well.

Thanks for responding!

**Comment by alexbuijs** [comment]
> My Docker data is also encrypted in DSM, maybe this is part of the problem...

This! I spent a whole day recreating gitlab images as well, until I found out the permission issues have to do with the encrypted shared folder. I need encryption on the Gitlab data directory. Does anybody know why encrypted folders behave differently from non-encrypted folders in DSM and how to fix this issue?
