### ISSUE TITLE
incomplete relative url changes

### ISSUE THREAD

**Issue by r2evans** [sameersbn/docker-gitlab#1191]
The use of `GITLAB_RELATIVE_URL_ROOT` is missing one step. Referencing https://docs.gitlab.com/ce/install/relative_url.html, these are all good in my installation:

- `gitlab/config/initializers/relative_url.rb`
- `gitlab/config/gitlab.yml`
- `gitlab/config/unicorn.rb`
- `gitlab-shell/config.yml`

But the last change is not being done:

> Make sure you have copied the supplied init script and the defaults file as stated in the installation guide. Then, edit /etc/default/gitlab and set in gitlab_workhorse_options the -authBackend setting to read like:

>     -authBackend http://127.0.0.1:8080/gitlab

But `/etc/init.d/gitlab` contains:

    gitlab_workhorse_options="-listenUmask 0 -listenNetwork unix -listenAddr $socket_path/gitlab-workhorse.socket -authBackend http://127.0.0.1:8080 -authSocket $rails_socket -documentRoot $app_root/public"

I would expect it to be

    gitlab_workhorse_options="-listenUmask 0 -listenNetwork unix -listenAddr $socket_path/gitlab-workhorse.socket -authBackend http://127.0.0.1:8080/gitlab -authSocket $rails_socket -documentRoot $app_root/public"
    ## (the only difference is here ----->   -->   -->   -->   -->   -->   -->   -->   -->   -->   -->   -->   -->   -->   -->   -->   -->   -->    ^^^^^^^

Currently this is on 9.0.6.

**Comment by r2evans** [comment]
Still the case with 10.2.6.

**Comment by paddy-hack** [comment]
The Docker image uses `supervisor` to start the various jobs.  The `/etc/supervisor/conf.d/gitlab-workhorse.conf` snippet does include the `{{GITLAB_RELATIVE_URL_ROOT}}` that is replaced by the value of the environment variable on startup.  In a running container the `-authBackend` option should be set as you expect.  You can check the `supervisor` snippet of a running instance and/or have a look at the `ps -HAf | cat` output to verify that `gitlab-workhorse` is indeed running with a `-authBackend` option that has the value of `GITLAB_RELATIVE_URL_ROOT` appended.

Confirmed for 11.1.4 but this was added in a541669f36f8be8abaa774b9fcc6567056d502cd so should have been running just fine since 8.3.0.

\# Too bad you're issue didn't turn out to be cause of my current relative URL root woes :disappointed_relieved:

**Comment by r2evans** [comment]
Thank you for the reminder, @paddy-hack. Good catch about `/etc/supervisor/conf.d/gitlab-workhorse.conf`, I missed that.

I'm currently running 11.0.5 and do in fact see the correct reference in the config file:

```
...
command=/usr/local/bin/gitlab-workhorse
  -listenUmask 0
  -listenNetwork tcp
  -listenAddr ":8181"
  -authBackend http://127.0.0.1:8080/gitlab
  -authSocket /home/git/gitlab/tmp/sockets/gitlab.socket
  -documentRoot /home/git/gitlab/public
  -proxyHeadersTimeout 5m0s
...
```

and confirmed that the running process is also correct:

```
$ ps faxwww | grep [w]orkhorse
  1053 ?        Sl     0:50 /usr/local/bin/gitlab-workhorse -listenUmask 0 -listenNetwork tcp -listenAddr :8181 -authBackend http://127.0.0.1:8080/gitlab -authSocket /home/git/gitlab/tmp/sockets/gitlab.socket -documentRoot /home/git/gitlab/public -proxyHeadersTimeout 5m0s
## (I see it here ----->   -->   -->   -->   -->   -->   -->   -->   -->   -->   -->   -->   -->   -->   -->   -->   -->   -->   -->   -->   -->  ^^^^^^^
```

So with that, it appears to be not-a-problem anymore.
