### ISSUE TITLE
redis auth support

### ISSUE THREAD

**Issue by laoshancun** [sameersbn/docker-gitlab#1453]
hi.
how to pass redis password to gitlab?

**Comment by drubin** [comment]
It doesn't currently seem to be possible. 

The config file https://github.com/sameersbn/docker-gitlab/blob/master/assets/runtime/config/gitlabhq/resque.yml#L17

The redis checks https://github.com/sameersbn/docker-gitlab/blob/master/assets/runtime/functions#L248

Originally I thought you could hack `REDIS_HOST` to embed the `user:pass` but because of the checks that won't work. 

It would be a nice feature for Redis nodes that are not running on the machine to support REDIS_URI configuration option and create the uri and connect via the `-u` option but that was only added in 3.2.1 and the redis-cli version bundled with this version is `2.8.4`

**Comment by drubin** [comment]
there is also a pretty old PR for this https://github.com/sameersbn/docker-gitlab/pull/1026

**Comment by laoshancun** [comment]
how about merge #1026 to master? @sameersbn

**Comment by phenomax** [comment]
I'd also look forward to this! ping @solidnerd
