### ISSUE TITLE
Docker Image Size

### ISSUE THREAD

**Issue by ulrichSchreiner** [sameersbn/docker-gitlab#1502]
i think it would be ok to add these two lines at the end of "install.sh"
~~~
rm -rf ${GITLAB_HOME}/.cache 
rm -rf ${GITLAB_INSTALL_DIR}/node_modules
~~~
which deletes the yarn-cache and the sources of the JS-node_modules. it shoud reduce the image size a few hundred megs.

**Comment by mikehaertl** [comment]
Shouldn't this rather be in the `Dockerfile` at the end of the block where all the packages are installed? Because each single command in there will create a file layer that will always consume the same space. Thus removing stuff in a later commands doesn't reduce the image size.

**Comment by solidnerd** [comment]
Hey @ulrichSchreiner,
yes I agree with you.  The main reason why i didn't delete those things is that it would break some functionality of the image. The problem will come when you are setting gitlab under an own context instead of reserving a full domain. For this case all assets needs to be regenerated again.

@mikehaertl  install.sh  will be executed in one layer so it will be working.

**Comment by ulrichSchreiner** [comment]
@solidnerd ok, understand. i'll close this issue
