### ISSUE TITLE
chown of ${GITLAB_HOME}

### ISSUE THREAD

**Issue by ulrichSchreiner** [sameersbn/docker-gitlab#1503]
hi,

what is the reason of the line
~~~
chown -R ${GITLAB_USER}: ${GITLAB_HOME}
~~~
in the `install.sh`? i understand that volumes, where data is written must be owned bit the gitlab user, but `GITLAB_HOME` is the whole ruby-code (including vendored), go-code (gitaly, workhorse), ... much of this code is only for execution.

my main problem is: when using overlay2-FS in docker and also specifying a specific `USERMAP_UID` which differs from the default, the startup of the whole container is endlessly long, because the whole directory is about 2G with thousands of files. every one is now `chown`d. 

and overlay2-fs also store's diff-directories in `/var/lib/docker/` which also now has always very big diff-directory only because i have another UID/GID for the gitlab user. 

to be clear: the chown is absolutey neccessary for mounted volumes where data is written. the question is: why is this done for the whole executable code too.

**Comment by r2evans** [comment]
I think that [that line](https://github.com/sameersbn/docker-gitlab/blob/master/Dockerfile#L55) is only run when building the container, not when running it. It is in [`functions#L1168`](https://github.com/sameersbn/docker-gitlab/blob/3525e260fb3793826f1562a05c8f48deb41e2535/assets/runtime/functions#L1168), though, and perhaps this change might be more efficient?

```diff
 @@ -1168 +1168 @@ map_uidgid() {
 -    find ${GITLAB_HOME} -path ${GITLAB_DATA_DIR}/\* -prune -o -print0 | xargs -0 chown -h ${GITLAB_USER}:
 +    find ${GITLAB_HOME} -path ${GITLAB_DATA_DIR}/\* ! -user ${GITLAB_USER} -prune -o -print0 | xargs -0 chown -h ${GITLAB_USER}:
```

The underlying problem, though, is that what has been assigned as `${GITLAB_USER}` externally does not match `/etc/passwd`, so this patch won't work since `git` internally still maps to 1000 regardless of what was set up. @solidnerd , does this sequence make sense?

- on startup, update `/etc/passwd` with the provided `GITLAB_USER` and `USERMAP_UID`
- instead of a global overwrite all owners with a blind `chown`, use the above patch for conditional `chown`

Does it make sense?

**Comment by ulrichSchreiner** [comment]
hi,
i think you are right that `install.sh` is only executed when building. but your code is run on startup and i do not get, why the whole tree of sourcecode has to be chown'ed to the new UID/GID?

the UID/GID of the `git` user is changed in `map_uidgid` a few lines in front of the `find` statement. but my understanding of the whole `find` is that
~~~
find ${GITLAB_HOME} -path ${GITLAB_DATA_DIR}/\* -prune ..
~~~
matches *everything* inside of `GITLAB_HOME` except the data directory. so really everything is chown'ed. every ruby-file, go-sources, vendored go-sources, ... every file under `"/home/git` (except the data files),

for most of the files i don't think this is necessary, because most files are sources and/or executables. the do not need to be owned by the `git` user.

you can test it very easy: if you have a docker with overlay2-FS use the given `docker-compose.yml` and add a `- USERMAP_UID=99` (99 is nobody on my system). now try a `docker-compose up` and wait ....  you now see `Mapping UID and GID for git:git to 99:99` in the output.

in a second shell you can do a `ps auxf | grep chown` and see some chown's with thousands of parameters like `chown -h git: /home/git/gitlab/tmp/cache/assets/sprockets/v3.0/...` 

in my case i simply quit after waiting mor than 10 minutes ...

so i cannot run this image with overlay2.

**Comment by Kristaba** [comment]
Another user in the same usecase here...
Switched my Docker config to use `overlay2` and it just made the Gitlab image absolutely unusable (~40 minutes to start, instead of tens of seconds with default `devicemapper`).

This [line in file functions](https://github.com/sameersbn/docker-gitlab/blob/9111c8dced43d7fbbf1d1c1f1e3ca11981122aa8/assets/runtime/functions#L1235) causes thousand of files to be chown'ed at startup, when a UID/GID mapping is used.
Other projects such as [conda forge](https://github.com/conda-forge/docker-images/issues/63) or [jupyter](https://github.com/jupyter/docker-stacks/issues/81) appear to had the same issue for different reasons at some point and «solve» them by avoiding the chmod/chown.
However, a performance degradation which is **that** order of magnitude (compared to loopback devicemappers or AUFS) seems to be a real issue in `overlay2` itself too...

So to recap:
- `overlay2` is incredibly slow for performing chmod/chown operations (and require a full copy of each modified file)
  - maybe this should be reported to the kernel team behind `overlay2`, even if it is probably quite deeply caused by the underlying structure of the file system...
- Gitlab docker init script use to chown on all the gitlab files in the image if GID/UID mapping is required
  - if a workaround was available for this use case, it could helpful for people using `overlay2` storage driver

Is there any idea of a quick workaround, not too much dirty?
I mean, maybe just setting sufficient group permissions at image *build* time, and adding the git user to this group at *run* time may be enough?
I don't know the gitlab code enough to know all the places where user/group will matter, but does someone have an idea about it?

Before to have a fix for that, it may be great to have some kind of warning in the readme.
Like «Warning: using `overlay2` storage driver with docker is known to cause high performance issue with this image. See <this issue>. » ?
