### ISSUE TITLE
docker image build failed 11.6.0

### ISSUE THREAD

**Issue by colachg** [sameersbn/docker-gitlab#1823]
I have cloned the project and build successfully on my laptop.

Is there something wrong in dockerhub runner?

https://hub.docker.com/r/sameersbn/gitlab/builds

**Comment by solidnerd** [comment]
Hey,

yep it seems so because ci is also runned successfully. The problem is that I can't retrigger a build manually on docker hub. I'll provide the images from ci.

https://circleci.com/gh/sameersbn/docker-gitlab/308?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by solidnerd** [comment]
It's done you can use them now. Have fun with the new release.
