### ISSUE TITLE
Project status maintainers and support regarding security issues

### ISSUE THREAD

**Issue by drubin** [sameersbn/docker-gitlab#1999]
HI @sameersbn and @solidnerd 

I would firstly like to thank you for all the hard work and effort you are both doing to support and maintain this package it is clear you are one of the biggest Gitlab distributions out there. Many people including me, rely on this and your hard work and you made it possible to run gitlab inside docker even before gitlab supported this.

What is also becoming more clear is that the security releases and general upgrades lag behind the official releases for many weeks or months. While I totally understand that you both are busy and have fulltime jobs (as most of us do). 

This is also not acceptable as it creates massive security and liability risks for the users of this project and distribution.

I would like to request we ask the community and maintainers to promote additional maintainers that they can help with the extra burden of keeping up to date with the latest security and patch releases testing and verifying that releases work.

Please don't think of this as complaining I would like to try and help and I think the best way is to get additional core maintainers on board.

Please, let's try to figure out how best to enable the community to keep using this project.

**Comment by solidnerd** [comment]
Hey @drubin,

I don't see this as complaining, but you are right our velocity in rolling out new versions gets slower and slower. 
I think this comes from two points: 

1. The docker hub has a breaking change in the whole deployment. Currently, I can't see any builds on docker hub anymore also to configure them. sameersbn is the only person that can change it. Because of this, I need to deploy independent from the docker hub. At the moment I use my personal infra to able to deploy this. Why we can't do this in the whole public. Is that we don't have a technical user for deployments. So we use our personal accounts to deploy this (docker hub & GitHub). 

2. The missing focus of the project from my side.

I think it's good timing to add one or two more persons to help to maintain this image. I would appreciate it if we can add the people.

The hardest part of opening it to more maintainers is to add a technical deployment user (As I described above). Currently, we deploying the images with our personal accounts. 
This is the current caveat that stops us from having an independent process without our personal accounts. 

I think this needs also to be changed. 

What do you think @sameersbn? 

I hope this answers your question a little bit. I think we need to discuss this further

**Comment by drubin** [comment]
Hey @solidnerd 

Could you maybe describe what part of `1` broke that is critical to the release flow? I don't fully understand why you need to manually edit anything.

Also would changing official registries to either gitlab or quay help with this?

**Comment by drubin** [comment]
Considering the following I going to close this. 

It's clear this project is no longer actively maintained and that is totally fine, the lack of communication and community involvement is not. 

https://github.com/sameersbn/docker-gitlab/issues/2103
https://github.com/sameersbn/docker-gitlab/issues/2104 

We have moved off this docker image onto the official distro. 

Thanks for the hard work maintaining this image I can't imagine it was easy to do alone.
