### ISSUE TITLE
Private registry image running locally

### ISSUE THREAD

**Issue by zeynepkoyun** [sameersbn/docker-gitlab#2463]
Hi @kkimurak
How can I run images stored in gitlab_rails['registry_path'] directory directly with file path without using "docker pull" command?

**Comment by sachilles** [comment]
Hi,

probably I don’t really understood your question. But, in order to check out images from any docker registry (even from GitLab), you'll need to use `docker pull` in order to get a copy of the docker image on your docker host.

**Comment by kkimurak** [comment]
@zeynepkoyun 
Hi, I'm late

1. Your question is bit strange and complex but I have confirmed that it can be done by collecting necessary files (each layer archive, layer info json, image manifest json and so on) from registry directory and create tar archive that mimics the format that created by the `docker save` command. Load it using `docker load`. (off course you might be requried to have access permission to the directory)
2. Your question is purely out of scope. There is nothing helpful info for you. Please close this issue and move to anywhere like stackoverflow then notice me. I will take an effort to try to restore my script from trash box.

@sachilles sorry for late. Please feel free to close this issue. This can be labeled as `invalid` or `wontfix` so that we don't have to take care this in this repository.

**Comment by sachilles** [comment]
As desired, I assign labels and close the issue. 😄
