### ISSUE TITLE
Errors literally everywhere

### ISSUE THREAD

**Issue by snaildos** [sameersbn/docker-gitlab#2499]

**Comment by snaildos** [comment]
Whoops, accidently created without description 😬 
Here, pretty much...
![image](https://user-images.githubusercontent.com/46210117/151308722-135b0516-e0ca-4361-a7de-9dc5f51d6627.png)

Groups, WebIDE, CI, all errors.

**Comment by kkimurak** [comment]
1. What version of `sameersbn/gitlab` are you running?
2. How did you configure the image? (e.g. submitting `docker-compose.yml` is easy way to share your configuration. Don't forget to mask your secrets values)
3. There are so many reasons such error happen, and we cannot estimate it from browser. Please take a look into log file (`/var/log/gitlab/gitlab/production.log` and so on).

**Comment by snaildos** [comment]
Hello, thanks for the reply.
1. I'm using the :latest tag, I just repulled before you commented.
2. 2. I just copied and pasted it, https://www.toptal.com/developers/hastebin/xiwiponaqu.http
3. No such file or directory, Am I supposed to do it in the container?

**Comment by kkimurak** [comment]
1. Alright, so I think you're using v14.6.3 now.  
2. well, the code will not work.
3. Yes off course, check the log file in container. Sorry for not clarify.

OK, the problem is the configuration file. I just checked it briefly yet, but there are so many parameter mismatch. For example

- `DB_NAME`, `DB_PASS` and `DB_USER` in gitlab's environment field is differ from postgresql's one). GitLab will not be able to access the database. 
- `GITLAB_HOST` MUST NOT contain `http(s)://`. 
- SMTP will not work : all of `SMTP_XXX` settings are invalid. 

Try to fix them - at least `DB_**` must be fixed. I hope you're standing on beginning at all and about to start setting up. 

1. run `docker-compose down gitlab` to stop running gitlab 
2. run `docker-compose rm gitlab` to remove stopped gitlab container
3. edit `docker-compose.yml` and correct DB connection variables and so on
4. run `docker-compose up -d gitlab` to relaunch gitlab
5. run `docker-compose log --follow gitlab` to see what's going on (press Ctrl+C to stop looking into log).

good luck,

**Comment by snaildos** [comment]
Hello, thanks for the reply and support. I'm not getting the db part, what havw I done wrong? If the connection isnr established then how can I even make and delete repos?
Regards,
SnailDOS

**Comment by snaildos** [comment]
As well, the fields that are xxx'd is me redacting them. Maybe it wasnt clear?

**Comment by snaildos** [comment]
👋, final update, your suggestion for the https host worked. Thanks so much, everything is working as expected.
Regards,
SnailDOS

**Comment by kkimurak** [comment]
> As well, the fields that are xxx'd is me redacting them. Maybe it wasnt clear?

Ah, ok. I made a mistake because you said "copy and paste". It's good to mask.  
However, since the password and user name actually set in the database are written in the environment variables of postgresql, I think it would be good to mask that as well. 

so glad to hear works fine.
