### ISSUE TITLE
config other email except gmail

### ISSUE THREAD

**Issue by stardustman** [sameersbn/docker-gitlab#2520]
how to config gitlab server's notification email not gmail?
If don't want to use env variable from [available-configuration-parameters](https://github.com/sameersbn/docker-gitlab#available-configuration-parameters). could I use 
```ruby
gitlab_rails['smtp_enable'] = true
gitlab_rails['smtp_address'] = "smtp.exmail.qq.com"
gitlab_rails['smtp_port'] = 465
gitlab_rails['smtp_user_name'] = "xxxx@xx.com"
gitlab_rails['smtp_password'] = "password"
gitlab_rails['smtp_authentication'] = "login"
gitlab_rails['smtp_enable_starttls_auto'] = true
gitlab_rails['smtp_tls'] = true
gitlab_rails['gitlab_email_from'] = 'xxxx@xx.com'
```
in the docker container?

**Comment by kkimurak** [comment]
No, `gitlab_rails` keyword is for omnibus-installed gitlab and official `gitlab/gitlab-**` image.  
This, `sameersbn/gitlab` image, provides source-installed gitlab. So you need to set such variables in `/home/git/gitlab/config/gitlab.yml` (and more) in container.  
I don't know why you are going to avoid env variables but I strongly recommend you to use them, like `SMTP_ENABLED`..

If you really do need to do that, you can change the settings without restarting the container in the following ways:

- Edit the configuration file. Since common text editors are not installed, you'll have to use commands like `sed` and` awk`.
- Run `supervisorctl restart <service-name>` as root in the container to restart the services in the container.  
Executing `supervisorctl status` checks what services are running in container and managed by `supervisor`.  

However, these settings will be rolled back the next time the container is restarted. So I don't recommend this.

**Comment by stardustman** [comment]
I don't want to recreate the container, because the [issues/2521](https://github.com/sameersbn/docker-gitlab/issues/2521).
I have config the `mail` server not the gmail, it is the Tencent enterprise email. the docker-compose.yml gitlab config is
```yaml
   - SMTP_ENABLED=true
    - SMTP_DOMAIN=exmail.qq.com
    - SMTP_HOST=smtp.exmail.qq.com
    - SMTP_PORT=465
    - SMTP_USER=devops-admin@juzi.bot
    - SMTP_PASS=xxxyyyzzz
```
then I use `docker-compose up -d` to restart the gitlab, but the config still not work. what's the reason? Is there something I don't config?

**Comment by stardustman** [comment]
according to (https://docs.gitlab.com/omnibus/settings/smtp.html#qq-exmail)[https://docs.gitlab.com/omnibus/settings/smtp.html#qq-exmail], missing `smtp_tls`
is there a doc to explain the ([available-configuration-parameters](https://github.com/sameersbn/docker-gitlab#available-configuration-parameters)) variables mapping to (https://docs.gitlab.com/omnibus/settings/smtp.html#qq-exmail)?

**Comment by kkimurak** [comment]
`SMTP_TLS` is what you're looking for, I think.

**Comment by stardustman** [comment]
Yes, after add `STMP_TLS` it works.
