### ISSUE TITLE
Howto properly add the NGINX_CUSTOM_GITLAB_SERVER_CONFIG to docker-compose.yml

### ISSUE THREAD

**Issue by Basti-Fantasti** [sameersbn/docker-gitlab#2536]
Hi all,

I've tried to add the new switch `NGINX_CUSTOM_GITLAB_SERVER_CONFIG` to my docker-compose file.
I added it as stated in the PR #2517 from @kkimurak 

but when adding the config entry accordingly to my docker-compose file it throws an error.

````yaml
    environment:
      NGINX_CUSTOM_GITLAB_SERVER_CONFIG: |
          location /-/plantuml/ {
            proxy_cache off;
            proxy_pass  http://plantuml:8080/;
          }

````

Error:

````bash
ERROR: yaml.parser.ParserError: while parsing a block mapping
  in "./docker-compose.yml", line 31, column 5
expected <block end>, but found '<block mapping start>'
  in "./docker-compose.yml", line 173, column 7
````

When I enter the value like the other optional parameters, as a single row parameter:

````yaml
    environment:
      - NGINX_CUSTOM_GITLAB_SERVER_CONFIG=location /-/plantuml/ {\n    proxy_cache off;\n    proxy_pass  http://plantuml-server:8080/;\n}\n

````
or like this:

````yaml
    environment:
      - NGINX_CUSTOM_GITLAB_SERVER_CONFIG="location /-/plantuml/ {\n    proxy_cache off;\n    proxy_pass  http://plantuml-server:8080/;\n}\n"

````

the container comes up, but nginx keeps crashing with error 1

**Comment by kkimurak** [comment]
Hi, thanks reporting.  

I dont know how is your `docker-compose.yml` written, but from your report I assume that most likely [top `docker-compose.yml` of this repository](https://github.com/sameersbn/docker-gitlab/blob/master/docker-compose.yml), right?  

Then you cannot mix `- KEY=value` style and `KEY: value` style in `environment:` section. First configuration you wrote is reporting error standing on this restriction.

Second and third configurations are valid as yaml, but the newline (`\n`) will be escaped and treated as is (I mean `\\n` will be passed to docker), so you will find invalid nginx configuration generated.

```sh
$ docker exec -it gitlab tail -n 10 /etc/nginx/sites-enabled/gitlab
  error_page 500 /500.html;
  error_page 502 /502.html;
  error_page 503 /503.html;
  location ~ ^/(404|422|500|502|503)\.html$ {
    root /home/git/gitlab/public;
    internal;
  }

  location /-/plantuml/ {\n    proxy_cache off;\n     proxy_pass  http://plantuml:8080/;\n  }
}
```

That's why nginx keeps crashing with error 1 - it's quite simple because the configuration is invalid. 

We have some choice to fix this but I personally recommend you to use dictionary style whole in environment section. In [example `docker-compose.yml`](https://github.com/sameersbn/docker-gitlab/blob/master/docker-compose.yml)

>````yaml
>    environment:
>    - DEBUG=false
>
>    - DB_ADAPTER=postgresql
>    - DB_HOST=postgresql
>    - DB_PORT=5432
>    - DB_USER=gitlab
>    - DB_PASS=password
>    - DB_NAME=gitlabhq_production
>````

With mapping style we can write like this:

```yaml
    environment:
      DEBUG: 'false'

      DB_ADAPTER: postgresql
      DB_HOST: postgresql
      DB_PORT: 5432
      DB_USER: gitlab
      DB_PASS: password
      DB_NAME: gitlabhq_production
````

Note that boolean should be quoted (because yaml has no boolean. only string or number)
Now you can use my example as is.

If you really need to keep `- KEY=value` style, see https://stackoverflow.com/questions/3790454/how-do-i-break-a-string-in-yaml-over-multiple-lines (but you will loss your time, I think)

**Comment by kkimurak** [comment]
P.S. use `docker-compose config` to validate your configuration file. yaml is useful but the syntax is little bit complex..

**Comment by Basti-Fantasti** [comment]
HI and thanks for your reply and your detailed explanation.

yes, my docker compose file is like then one posted in this repo with the '=' style.

Can I easily change it to the ':' style?

**Comment by Basti-Fantasti** [comment]
ok, now finally I got it work 🥳 

Here's what I did:

- Updated my docker-compose file to colon style / dictionary style
- added the section like this:

````yaml
      NGINX_CUSTOM_GITLAB_SERVER_CONFIG: |
        location /-/plantuml/ {
          proxy_cache off;
          proxy_pass  http://172.21.0.250:8080/plantuml/;
        }

````

inside the gitlab config I had to set my **full host name** for the redirect to work.
So setting the value to localhost or local IP did not work.

So the entry in gitlab settings looks like this:

`https://my.gitlab.install/-/plantuml/`


now I can use the plantuml syntax inside gitlab like this:

````
````plantuml
@startuml
Bob -> Alice : hello
Alice -> Bob : hi
@enduml
````

It is rendered correct.

**Comment by kkimurak** [comment]
glad it works:)  
Please close this issue if it is okay.
