### ISSUE TITLE
docker-compose data restore! VERY URGENT!

### ISSUE THREAD

**Issue by Stone-ChenLijun** [sameersbn/docker-gitlab#2540]
Hi, I was hit a very urgent event, I LOST MY GITLAB DATA which contains last three years data.

My company was a small company, it bought a qnap nas with gitlab run on it which was powered by docker-compse.
Today morning , I change the docker-compose.yml  and apply it. After it reboots, all the data was lost.

All I change is add 'RACK_ATTACK_ENABLED: true' before image: sameersbn/gitlab:11.10.4.
When occured data lost, I recover the docker-compose.yml but data is still lost.

NOW IS THERE ANY WAY I CAN DO TO RECOVER MY DATA?

Below is the docker-compose.yml:
networks: {}
services:
  gitlab:
    depends_on:
    - redis
    - postgresql
    environment:
      DB_ADAPTER: postgresql
      DB_HOST: postgresql
      DB_NAME: gitlabhq_production
      DB_PASS: password
      DB_PORT: 5432
      DB_USER: gitlab
      GITLAB_HOST: fake.myqnapcloud.com
      GITLAB_PORT: 10080
      GITLAB_SECRETS_DB_KEY_BASE: qcs-gitlab-app
      GITLAB_SECRETS_OTP_KEY_BASE: qcs-gitlab-app
      GITLAB_SECRETS_SECRET_KEY_BASE: qcs-gitlab-app
      GITLAB_SSH_PORT: 10022
      REDIS_HOST: redis
      REDIS_PORT: 6379
      GITLAB_TIMEZONE: Asia/Shanghai
      SMTP_ENABLED: 'true'
      SMTP_DOMAIN: mail.163.com
      SMTP_HOST: smtp.163.com
      SMTP_PORT: 465
      SMTP_USER: account
      SMTP_PASS: password
      SMTP_STARTTLS: 'true'
      SMTP_TLS: 'true'
      SMTP_AUTHENTICATION: login
    image: sameersbn/gitlab:11.10.4
    ports:
    - 10080:80
    - '10022:22'
    restart: always
  postgresql:
    environment:
      DB_EXTENSION: pg_trgm
      DB_NAME: gitlabhq_production
      DB_PASS: password
      DB_USER: gitlab
    image: sameersbn/postgresql:10
    restart: always
  redis:
    command:
    - --loglevel warning
    image: sameersbn/redis:4.0.9-1
    restart: always
version: '3'
volumes: {}

**Comment by Stone-ChenLijun** [comment]
I found the data was locate in [/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/volumes/01ac44f121c034299a0c969144042c9cc50cf50948b179f269f3a366af73874c/_data.
It seems all the data was still there, but why gitlab didn't use it?

**Comment by john2021wick** [comment]
对比一下新旧compose文件里面的volumes名称是否一致

**Comment by kkimurak** [comment]
First of all: If it is possible, please take a backup of whole disk at your own risk. Here "you" does not mean you personally, but your team. Please consult with your team members if necessary.

Then read documentation : https://docs.docker.com/storage/volumes/#backup-restore-or-migrate-data-volumes  

----

This image `sameersbn/gitlab` declares some important directories [as volume](https://github.com/sameersbn/docker-gitlab/blob/11.10.4/Dockerfile). `/home/git/data`(main data storage that contains build artifacts, git repositories, uploaded contents and so on) and `/var/log/gitlab` (Logs of gitlab and related applications) for example.  
In most case the "volume" is associated with container. "volume" is persisted by default so will not be removed even you stop container. But when you run `docker-compose up` (or something else) after you change configuration, new container and new volume are created and the old volume (for your case `01ac44f121c034299a0c969144042c9cc50cf50948b179f269f3a366af73874c`) will not be reused. That's why your "new" gitlab container didn't load them.

The official documentation will tell you how to backup, restore or migrate data volumes from stopped container to new container : https://docs.docker.com/storage/volumes/#backup-restore-or-migrate-data-volumes  

Note that you may want to fix permission of restored data files. You can achieve this automatically with `app:sanitize` option (e.g. `docker run --name gitlab -d [OPTIONS] sameersbn/gitlab:11.10.4 app:sanitize`). This is option for [`entrypoint.sh`](https://github.com/sameersbn/docker-gitlab/blob/11.10.4/entrypoint.sh#L33-L35) to invoke [a function `sanitize_datadir()` defined in `assets/runtime/functions`](https://github.com/sameersbn/docker-gitlab/blob/11.10.4/assets/runtime/functions#L1440-L1480).

**Comment by Stone-ChenLijun** [comment]
> 
Thanks for your help. But my leader has order all developers to register and upload all the projects agian. I was told to do not change anything again.
