### ISSUE TITLE
Remove a gitlab container

### ISSUE THREAD

**Issue by sydneyhenrard** [sameersbn/docker-gitlab#261]
Hi, 

When I remove a container `docker rm gitlab` and then I create a new one. I still have my users and projects.

I would like to know what is happening when I remove a gitlab container. What data am I losing?

Thanks

**Comment by cedvan** [comment]
Hi,

- For **save files** in Gitlab (repositories, avatars, ...), use `-v /path/save/data/in/host:/home/git/data`
- For **save database** (users, projects, rights, ...) :
    - With **mysql container internal** : use `-v /path/save/database/in/host:/var/lib/mysql` in command docker run *gitlab*
    - With **mysql container external** : use `-v /path/save/database/in/host:/var/lib/mysql` in command docker run *mysql* and use `--link mysql:mysql` in command docker run *gitlab*
    - With **postGreSQL container external** : use `-v /path/save/database/in/host:/var/lib/postgresql` in command docker run *postgresql* and use `--link postgresql:postgresql` in command docker run *gitlab*

**Comment by sameersbn** [comment]
@sydneyhenrard scratch the *mysql container internal* part of @cedvan' response. The internal mysql server does not exist anymore.

To extend on @cedvan' response. The gitlab container does its best to store its data in volumes. So long as you have the volumes mounted, your gitlab data is safe. This includes your repositories, etc.

For the mysql/postgresql data, the required volumes have to be mounted for these containers so that the data is not lost when the container is removed.

**Comment by cedvan** [comment]
Yes sorry, internal mysql has been removed :)
