### ISSUE TITLE
Documentation inconsistency - Linking database container to gitlab

### ISSUE THREAD

**Issue by danielhass** [sameersbn/docker-gitlab#280]
Hi @sameersbn,
first I'd like to thank you for your great work building all these nice docker images.

I'm new to docker and started playing around with your gitlab container. I used your postgresql container for the database part and stucked to get things working. 

The logs of the gitlab container showed this error to me:
`psql: FATAL:  password authentication failed for user "gitlab"`

So I read your documentation again and I think I spotted a little inconsistency.

At the beginning of "Linking to PostgreSQL Container" you're saying that 
`only DB_TYPE, DB_HOST and DB_PORT settings are automatically retrieved using the linkage. You may still need to set other database connection parameters such as the DB_NAME, DB_USER, DB_PASS and so on.`

At the end of this section I found this: 
`The image will automatically fetch the DB_NAME, DB_USER and DB_PASS variables from the postgresql container using the magic of docker links`

So what is true now? Should I set parameters like DB_NAME, DB_USER etc. or are they retrieved automatically?

**Comment by sameersbn** [comment]
@danielhass The documentation needs to be corrected. The container will get the `DB_HOST` and `DB_PORT` parameters from the linkage 100% of the time because the user does not have to specify anything for this to work (i.e. apart from specifying the `--link` option to the docker run command).

The image will also automatically get `DB_NAME`, `DB_USER` and `DB_PASS` from the linkage, provided that they have been specified when the postgresql image is started and also requires that the `DB_NAME` option specifies only a single database (the `sameersbn/postgresql` container allows you to create multiple databases via the `DB_NAME` option).

I hope this clarifies things.

**Comment by danielhass** [comment]
@sameersbn thank your for your fast answer. I will test the linking on my system again with this new knowledge in mind. If all works fine I will close this issue afterwards.
