### ISSUE TITLE
the DB password  which in docker-compose file is incorrect

### ISSUE THREAD

**Issue by alexwhen** [sameersbn/docker-gitlab#318]
the correct db password is "password"

**Comment by sameersbn** [comment]
@alexwhen are you referring to the latest version of the `docker-compose.yml` file?

**Comment by alexwhen** [comment]
@sameersbn of course,pls check docker-compose.yml
environment:
    - DB_USER=gitlab
    - DB_PASS=secretpassword  
    - DB_NAME=gitlabhq_production

the correct DB_PASS=password

**Comment by sameersbn** [comment]
@alexwhen I don't understand why you say that `secretpassword` is wrong. Is it because in the `README` i have used `DB_PASS=password`? If yes, then technically the two are unrelated since one uses docker-compose and the other is manually creation. However, I will change it to password in the `docker-compose.yml` file as well.

**Comment by alexwhen** [comment]
@sameersbn because when use docker-compose up,it said postgresql password is wrong,so i edit it ,and then success!

by the way,can you build a new yml for gitlab+redmine+gitlabci?
