### ISSUE TITLE
Autostart docker-gitlab

### ISSUE THREAD

**Issue by Z3roCoder** [sameersbn/docker-gitlab#344]
Is there currently any "good" way to autostart docker-gitlab on startup, as well as beeing able to say "service docker-gitlab start|stop|restart"?

**Comment by zetxx** [comment]
I believe that this question is not for here, you should see how you can create systemd service

**Comment by Z3roCoder** [comment]
I have tried it with systemd but I have no idea how to correctly manage the container to "start|stop|restart" correctly. And I haven't found an example online either.

Is there someone who already did this and could help me out?

**Comment by apeltzer** [comment]
Why don't you use the docker based --restart=always method?

**Comment by sameersbn** [comment]
@Z3roCoder docker docs lists sample systemd service configurations for launching containers https://docs.docker.com/articles/host_integration/. You can also use the `--restart=always` option as mentioned by @apeltzer

**Comment by sameersbn** [comment]
@Z3roCoder In case you are still at it, take a look at https://coreos.com/docs/launching-containers/launching/getting-started-with-systemd/

Closing issue for now.

**Comment by burkeazbill** [comment]
Sorry to comment on a closed issue, but I've just gotten into all this container stuff and this is the first app that I'm working with so I had a similar need - when the VM reboots, bring the containers back up. I went the easy route here by using docker-compose up -d 

The key thing here was to add
restart: always
in the docker-compose.yml. I added this immediately following each image: line so that each of the 3 images had the restart: always defined.

I am now able to reboot my VM and see gitlab up and running afterwards without having to spend the extra time figuring out the systemd stuff from that article.

It may be a good idea to just add this line to the sample .yml file that is provided in this repository.
