### ISSUE TITLE
Can't log in as root user

### ISSUE THREAD

**Issue by bennythomps** [sameersbn/docker-gitlab#400]
I tried logging in as the root user with default credentials and cannot log in. I am able to create a user and log in as that new user after confirming my email.

**Comment by sameersbn** [comment]
The root user is automatically created when the database is initialized 
for the first time. If for some reason this did not happen, then can you 
try deleting the database and starting the container again so that the 
db is reinitialized. Also delete the `tmp` directory from the data volume.

NOTE: this means you will lose any data that currently exists in the 
database.

On Thursday 06 August 2015 10:50 AM, Benny Thompson wrote:
> I tried logging in as the root user with default credentials and cannot log in. I am able to create a user and log in as that new user after confirming my email.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/sameersbn/docker-gitlab/issues/400
>

-- 
Sameer Naik

w: http://www.damagehead.com e: sameer@damagehead.com

**Comment by sameersbn** [comment]
were you able to resolve the issue? can this be closed?
