### ISSUE TITLE
Install fails when postgres password has / in it

### ISSUE THREAD

**Issue by intirix** [sameersbn/docker-gitlab#408]
The container keeps exiting because some sed statements are failing.  The sed statements fail with:
sed: -e expression #1, char 19: unknown option to `s'

I discovered this was the root cause by adding DEBUG_ENTRYPOINT into my environment.

P.S.  No rush on this issue.  I am changing the password to my postgres user.

**Comment by sameersbn** [comment]
@intirix there really in no way of fixing such issues in the image i think. As `sed` is used for the substitutions and because certain characters need to be escaped for bash, the onus is on the user to properly escape the variables. I know that this is a tough ask for newbies, the least one can do in avoid using special characters in the password and instead use long passwords (hash of some kind).

**Comment by JrCs** [comment]
Related issue: #516

**Comment by JrCs** [comment]
Fixed with #522
