### ISSUE TITLE
GITLAB_SECRETS_DB_KEY_BASE  is required after 8.0?

### ISSUE THREAD

**Issue by linlinlinlin** [sameersbn/docker-gitlab#432]
I am using 7.13.4 before today. And I didn't setup ``GITLAB_SECRETS_DB_KEY_BASE`` for my compose file.

Is ``GITLAB_SECRETS_DB_KEY_BASE`` is required after upgrade 8.0?

Because it will shows
```
ERROR: 
  Please configure the GITLAB_SECRETS_DB_KEY_BASE parameter.
  Cannot continue. Aborting...

```

**Comment by sameersbn** [comment]
Yes, it is required.

**Comment by linlinlinlin** [comment]
I am curious about the reason why the old version is not required but new version have to do it.

**Comment by sameersbn** [comment]
This parameters was originally used in the Gitlab CI image. In 8.0.0, since the two have been merged this variable is now part of Gitlab CE.

The parameter is used by GitLab's CI feature to encrypt any build script variables that you may define. Gitlab automatically generates this when not specified. But since it is a sensitive variable, we don't rely on this auto generated value because the lose of this variable would result in your builds failing and there will be no way to recover this until you have the original value that was set for this variable.

Due to this nature of the `GITLAB_SECRETS_DB_KEY_BASE` parameter, I have taken the decision that user should set specify the variable and is resposible for backing it up.
