### ISSUE TITLE
Sed error when trying to deploy on openshift

### ISSUE THREAD

**Issue by hodrigohamalho** [sameersbn/docker-gitlab#457]
I'm trying to deploy this image on openshift v3 using this:

```
oc new-app sameersbn/gitlab \
  -e 'DB_TYPE=postgres' \
  -e 'DB_HOST=172.30.173.71' \
  -e 'DB_PORT=5432' \
  -e 'DB_NAME=ramalhodb' \
  -e 'DB_USER=admin' \
  -e 'DB_PASS=redhat' \
  -e 'REDIS_HOST=172.30.16.81' \
  -e 'REDIS_PORT=6379' \
  -e 'GITLAB_SECRETS_DB_KEY_BASE=abc123' 
```  

The error message is:
sed: -e expression #1, char 24: unknown option to `s'

Any hint?

**Comment by sameersbn** [comment]
please add `-e DEBUG_ENTRYPOINT=1` in the environment. It will show you with `sed` substitution is erroring out. You will need to escape characters to resolve it.

**Comment by hodrigohamalho** [comment]
The error was here:

```
sudo -HEu git sed 's/{{GITLAB_PORT}}/tcp://172.30.185.58:22/' -i config/gitlab.yml
```

But can happen with any variable with the value have the char /.

If change the separator char it will work, eg:

```
sudo -HEu git sed 's#{{GITLAB_PORT}}#tcp://172.30.185.58:22#' -i config/gitlab.yml
```

**Comment by sameersbn** [comment]
@hodrigohamalho technically it can happen for any variable but generally happens in password fields. You need to escape such characters.

As for the issue you reported. `GITLAB_PORT` is expected to have a port number in the range 1 - 65535. Openshift seems to be creating the variable `GITLAB_PORT=tcp://172.30.185.58:22` due to which the `sed` substitution errors out.

Maybe it is automatically setting the app name to gitlab and creating a variable named `GITLAB_PORT` in the containers environment. If this is the case then try setting the application name to something else, eg. `gitlab-app` so that these variables do not conflict with the variables that the container expects. i think this is done using `--name` argument with `oc`. I have not used openshift before so I cannot say for sure.

**Comment by ebalsumgo** [comment]
@hodrigohamalho So @sameersbn is correct you can just pass in --name and get this working. But on the OpenShift end there is a problem, due to the fact that the image is trying to run as root and by default OpenShift does not allow such things. To get started you can do the following on your master:
1. oc login -u system:admin
2. oc edit scc privileged 
3. Change all RunAs to RunAsAny
4. oc edit scc restricted
5. Repeat step 3

NOTE: This allows images to run as root, this is not a good idea in production, but for right now I have not figured out the proper way to allow only certain Openshift projects to have RunAsAny vs RunAsUser,etc.

**Comment by ebalsumgo** [comment]
We are working on getting this going in a more OpenShifty way here https://github.com/michaelryanmcneill/docker-gitlab @michaelryanmcneill and I are working on it.

**Comment by hodrigohamalho** [comment]
Nice :)
To be honest I give up to put this image from sameers to work. I installed gitlab using gitlab-ce image and it is all embedded, so is less flexibe but more easy.

Thanks!

**Comment by michaelryanmcneill** [comment]
@hodrigohamalho can you let us know how you got the gitlab-ce image to work? We haven't been able to get it to work (doing git pulls, pushes, etc.) We can login, just can't anything to work outside of the web interface.

**Comment by hodrigohamalho** [comment]
@michaelryanmcneill sure, I make an step by step on my repo https://github.com/hodrigohamalho/openshift .
Gitlab specific instructions: https://github.com/hodrigohamalho/openshift/blob/master/gitlab/README.adoc

**Comment by michaelryanmcneill** [comment]
Awesome, thanks @hodrigohamalho, we'll give it a try!

**Comment by sameersbn** [comment]
closing issue. reopen if required.
