### ISSUE TITLE
cannot create regular file '/home/git/gitlab-shell/config.yml': Permission denied

### ISSUE THREAD

**Issue by fevxie** [sameersbn/docker-gitlab#494]
Hi, @sameersbn 

I met a issue when start gitlab container, following is the detail information , can you help to solve this problem ?

Basic information: 

OS: Debian GNU/Linux 8
Docker Verison infomation:

Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:37:20 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:37:20 UTC 2015
 OS/Arch:      linux/amd64

I have upgraded gitlab from 7.14.3 to 8.1.4, It working good,   But my Linux default system Partition  disk is not enough so, I move the  /var/lib/docker to another partition as following steps:

1.  service docker stop
2. add this line to /etc/default/docker  "DOCKER_OPTS="-g $(readlink -f /var/lib/docker)""
3. mv /var/lib/docker to /mnt/var_lib_docker/
4. ln -s  /mnt/var_lib_docker/   /var/lib/docker

then I start docker , everything seems good, and I start the postgresql and redis container. 

but when I start gitlab container,  It start failed,  the logs output: 

cp: cannot create regular file '/home/git/gitlab-shell/config.yml': Permission denied

what's the problem, why the gitlab container doesn't permission to home/git/gitlab-shell directory?

Thanks for advance

**Comment by sameersbn** [comment]
I don't think it is advisable to move `/var/lib/docker` like that. You should have disabled startup of docker from the boot sequence, restarted the host and then moved `/var/lib/docker` (using `rsync -a`).

Instead of creating a symlink you can specify `--graph=/my/new/path/` to the docker daemon arguments in `/etc/default/docker` on ubuntu hosts. 

Getting back to your issue. Looks like during the move, some file/directory permissions have changed which is causing the permission issue in the gitlab container. There is no way for me to tell what is causing the issue and how to resolve it as-is, my suggested resolution would be to remove the gitlab image and pull it again. 

Further, to be on the safest side, I would suggest deleting all your existing docker images and repulling all of them again. If you decide to go this route, then stop docker from the boot sequence, reboot, completely delete the location of the new graphs directory, update the docker daemon flags to point to the new graphs location, start docker and pull all images.

**Comment by fevxie** [comment]
Thanks @sameersbn, It's working after repulling gitlab image.
