### ISSUE TITLE
Upgrade to 8.5.1 High CPU

### ISSUE THREAD

**Issue by bscott** [sameersbn/docker-gitlab#624]
Ever since upgrading to 8.5.1, Gitlab is taking 95% of the CPU and responding very slowly, anyone else experiencing this?

Downgrading to 8.4.x is fine.

**Comment by rutsky** [comment]
@bscott so is a bug present or you just misconfigured something?

**Comment by sameersbn** [comment]
`8.5.4` has been released, can you try with the latest version?

Note: If you are using gitlab with a relative url then high cpu is expected for the first request (on every start). This is because gitlab goes and re-compiles the assets with the relative url which can take a while during which 100% of the CPU is used. If you are not using a relative url, then you should not see this.
