### ISSUE TITLE
bin/cp permission denied when docker run

### ISSUE THREAD

**Issue by haiyamicode** [sameersbn/docker-gitlab#63]
I got this error when trying to run the image, here's the full log:

```
Creating SSH2 RSA key; this may take some time ...
Creating SSH2 DSA key; this may take some time ...
Creating SSH2 ECDSA key; this may take some time ...
Creating SSH2 ED25519 key; this may take some time ...
invoke-rc.d: policy-rc.d denied execution of restart.
sshd: started
sudo: unable to execute /bin/cp: Permission denied
```

Version: latest (6.8.2)
Host machine: ubuntu 14.04 (with docker.io in the ubuntu repository)

**Comment by cmoulliard** [comment]
Problem is still there with image 7.9.4

````
docker logs gitlab
Creating SSH2 RSA key; this may take some time ...
Creating SSH2 DSA key; this may take some time ...
Creating SSH2 ECDSA key; this may take some time ...
Creating SSH2 ED25519 key; this may take some time ...
invoke-rc.d: policy-rc.d denied execution of restart.
````

Here is the instructions used to launch the container

````
docker run -itdP --name redis sameersbn/redis
docker run -itdP --name gitlab -e 'DB_TYPE=mysql' -e 'DB_HOST=192.168.59.103' -e 'DB_NAME=gitlabhq_production' -e 'DB_USER=gitlab' -e 'DB_PASS=xxxxx' -e 'GITLAB_SIGNUP=true' -e 'GITLAB_SSH_PORT=10022' -e 'GITLAB_PORT=10080' -p 10022:22 -p 10080:80 --env GITLAB_ROOT_PASSWORD=$GITLAB_PASSWORD --link redis:redisio --privileged sameersbn/gitlab:$GITLAB_VERSION

where $GITLAB_VERSION = 7.9.4
````

**Comment by sameersbn** [comment]
@cmoulliard the `invoke-rc.d: policy-rc.d denied execution of restart.` is expected when the container is started for the first time. Does the container exit at that point?

In case you are using redhat based or any selinux enabled host, then it could be because if the security context. I would  suggest mounting a volume for the data directory and apply the selinux policy as described in the data volume section of the readme

btw, the docker flags `-it` are not compatible with `-d`. You should use either one.

**Comment by AdamDanischewski** [comment]
I had this problem, I didn't "fix it", yet worked around it simply starting the sshd daemon on my own - instead of using the services/init.d/upstart. I recommend you test out starting sshd on your own (use the fully qualified path to sshd from root) and start it with -Dd to keep it from daemon'izing into the background and it will print debug information. If that's working fine, you can implement the workaround (starting it on your own) while you continue to search for the solution to the policy/upstart/init.d interactions.
