### ISSUE TITLE
Build failed 8.6.5

### ISSUE THREAD

**Issue by SolidNerd** [sameersbn/docker-gitlab#662]
Docker  Hub and quay.io are not happy. On Docker Hub it has the following error message: `Build failed: The command '/bin/sh -c bash ${GITLAB_BUILD_DIR}/install.sh' returned a non-zero code: 128`

@sameersbn

**Comment by sameersbn** [comment]
yea. shallow clones on gitlab.com are broken https://gitlab.com/gitlab-org/gitlab-ce/issues/15110
We just have to wait until it's fixed.

**Comment by splattael** [comment]
...or remove `--depth 1` (3x) from `install.sh`. It worked for me ;)

**Comment by sameersbn** [comment]
Will wait for gitlab.com to fix it. I don't want to package the entire git repositories in the image :smile:

**Comment by cybertk** [comment]
As 8.6.6 is out, can we skip to it?

**Comment by sameersbn** [comment]
Until the gitlab issue is fixed I dont think its a good idea to make new releases. I wish gitlab had maintained a mirror of gitlab-workhorse on github.

The possible resolutions I see are:
1. switch to source tarballs instead of doing a git clone. The problem with this is that gitlab will not be able to perform update check.

OR 

2. Clone the git repos from github and use tarballs for repos that are not available on github.

I prefer the second option. I will wait until tomorrow to act on it.

**Comment by cybertk** [comment]
+1 for second option

**Comment by carukc** [comment]
I also agree that option 2 sounds better.  I guess this will require a couple mods to install.sh.  Is there anything I can do to help?

Chris

**Comment by sameersbn** [comment]
new `8.6.6` release is out :smile:
