### ISSUE TITLE
Oauth GitHub

### ISSUE THREAD

**Issue by jffz** [sameersbn/docker-gitlab#691]
Followed this guide to enable GitHub Oauth: https://github.com/sameersbn/docker-gitlab#github
But Oauth doesn't works, telling me to enable it.

since i'm running docker_gitlab through docker-compose, i added following sections in my docker-compose.yml under gitlab section:

```` 
environment:
    - OAUTH_GITHUB_API_KEY=MY_KEY
    - AUTH_GITHUB_APP_SECRET=MY_SECRET
````

**Comment by SolidNerd** [comment]
You have a typo in your env. Replace `AUTH_GITHUB_APP_SECRET` with `OAUTH_GITHUB_APP_SECRET` and it should work.

**Comment by jffz** [comment]
fixed the typo, thanks.

But still having the message telling me taht Oauth isn't enabled.

https://gyazo.com/7142338defe6b0106c5988f4a9d6ded6

**Comment by SolidNerd** [comment]
Which version do you run ? And did you restart the container after the change ?

**Comment by jffz** [comment]
```
GitLab 8.7.0-rc3
GitLab Shell 2.7.0
GitLab API v3
Git 2.7.4
Ruby 2.1.8p440
Rails 4.2.5.2
PostgreSQL 9.2.15
```

Yes, i restarted the docker container (through docker-compose)
```
docker-compose down
docker-compose up -d
```

**Comment by SolidNerd** [comment]
I guess you run a different gitlab image and not this image. Could you show your docker-compose.yml ?

**Comment by jffz** [comment]
Yeah you're right, just seen it, I'm using the official gitlab image (https://hub.docker.com/r/gitlab/gitlab-ce/). Maybe should i consider moving to this one ?

**Comment by SolidNerd** [comment]
Yeah you should. In my opion this image is better than the offical because the official image use the omibus repository this one uses only the source and you can configure everythhing via enviroment variables. So if  you want to the official image all enviroment from this repository will not work. For more information about the offical image check the [documentation](https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/doc/docker/README.md). I run this image since gitlab 6.X and i got no problems and the upgrade is very easy aswell.
