### ISSUE TITLE
How to switch postgresql to mysql?

### ISSUE THREAD

**Issue by yuiopt** [sameersbn/docker-gitlab#785]
I am familiar with MySql,how to configure the docker-compose.yml to use mysql instead?

**Comment by SolidNerd** [comment]
Hey do you want migrate to mysql or do a fresh installation with MySQL .

**Comment by sameersbn** [comment]
@yuiopt I would not suggest using mysql. Gitlab works best with postgresql and is the database recommended by GitLab Inc.

**Comment by paddy-hack** [comment]
GitLab.com actively advised against MySQL.  I have one (legacy) MySQL instance that's stuck on 9.3.9 after I got it to use `utf8mb4`.  Currently looking at switching that to PostgreSQL using the [upstream documentation](https://docs.gitlab.com/ce/update/mysql_to_postgresql.html).  Seems to work mostly fine but I noticed that part of the activity info disappeared :disappointed:

**Comment by paddy-hack** [comment]
Additional info: the activity info disappearing may have been caused by me immediately upgrading my 9.3.9 after the MySQL → PostgreSQL switch all the way to 11.x, skipping stuff in between.  That's also advised against :unamused:  
Doing the GitLab upgrade a major.minor at a time, waiting for background migrations to complete, worked fine.
