### ISSUE TITLE
Error ssh_exchange_identification because of too many connections

### ISSUE THREAD

**Issue by brunolm** [sameersbn/docker-gitlab#969]
Is there a way I can edit the sshd configuration to include

```
MaxStartups 60
MaxSessions 60
```

So ssh works the way I need it to?

**Comment by solidnerd** [comment]
Hey,
yes of course. You can mount your sshd configration to `/etc/ssh/sshd_config` with your configuration options. But If you do that please merge this with current configuration of `/etc/ssh/sshd_config` in the container. Because during the build of the image we made some changes to the norma `sshd_config`. If you want to know what. Have a look at 
https://github.com/sameersbn/docker-gitlab/blob/master/assets/build/install.sh#L142 . If you have further question feel free to ask.

**Comment by brunolm** [comment]
On the version `8.9.6-1` if we were trying to mount the `sshd_config` but we were getting this error:

```
Initializing logdir...
Initializing datadir...
sed: cannot rename /etc/ssh/sedo00Jrn: Device or resource busy
```

Is this maybe a bug?

The workaround found at this moment was to build another image with a different entry point executing this:

```
#!/bin/bash

echo "MaxStartups 100:10:150" >> /etc/ssh/sshd_config
echo "MaxSessions 150" >> /etc/ssh/sshd_config

/sbin/entrypoint.sh $@
```

**Comment by zwopir** [comment]
this is still an issue. Mounting the sshd-config doesn't work because of
```
Loading /etc/docker-gitlab/runtime/env-defaults
Initializing logdir...
Initializing datadir...
sed: cannot rename /etc/ssh/sedzlJsCl: Device or resource busy
```
The gitlab docs explicitly name these parameters to fix the error (https://docs.gitlab.com/ee/topics/git/troubleshooting_git.html#ssh_exchange_identification-error)

It would be very nice if this PR could make it into the next release!

**Comment by camgian** [comment]
I used this as a quick workaround it seems to have given us relief at this point.

```
cd gitlab_tmp
docker cp  gitlab:/etc/ssh/sshd_config sshd_config
cp -f sshd_config sshd_config.orig
echo "MaxStartups 100" >> sshd_config
echo "MaxSessions 150" >> sshd_config
docker cp  sshd_config gitlab:/etc/ssh/sshd_config
docker exec gitlab /usr/sbin/service ssh restart
docker exec gitlab /usr/sbin/service ssh status

```

**Comment by zwopir** [comment]
thanks @camgian for the workaround!

Nevertheless and despite of various existing workarounds to this problem, it would be very nice if this PR (or an updated one) can make it into one of the next releases. 

Are there any chances? @solidnerd? Let me know if there's anything I could do!

**Comment by jprjr** [comment]
Hi stalebot, just leaving a reply so this isn't marked as stale.
