### ISSUE TITLE
Synology DS916+

### ISSUE THREAD

**Issue by oxoocoffee** [sameersbn/docker-gitlab#975]
Hello

I just got DS916+ and I installed GitLab 8.6.2-0019. After logging to GitLap in administrative panel I do see upgrade asap. But there is no available package when checking in Synology package manager.
How do you upgrade? Can I download needed packages?
Dependent packages are Docker (v1.11.2-0268) and MariaDB (v5.5.52-0069)

Cheers

**Comment by r2evans** [comment]
The fact that it came with 8.6.2 installed is disappointing, certainly, but I suggest your first outreach for support should be to them; unless I'm mistaken, I don't know that sameersbn and solidnerd are providing support to Synology customers.

Having said that, if your DS916+ has docker installed, and you can manage images yourselves (instead of being restricted to the images they want you to use), then theoretically it should be possible to use the database for the previous install through an upgrade process.

Caveat: if you have done nothing with the gitlab instance yet -- no projects and/or you can *easily* reintroduce the projects into a gitlab instance -- it will be considerably easier for you to just dump the current/old install and start with a fresh one, such as this one.

Assuming you cannot start over and should migrate, conventional advice and wisdom dictates that you incrementally upgrade through the latest release of each minor version. In order to start with your instance of gitlab, you'll need to know your database name, user, and password, so that you can modify the [`docker-compose.yml`](https://github.com/sameersbn/docker-gitlab/blob/master/docker-compose.yml) from this repo.

To start, you'll want to begin with a version like 8.6.7, the latest release of the 8.6 minor version. You can find that [here](https://github.com/sameersbn/docker-gitlab/releases/tag/8.6.7-1), the release of this repo at that gitlab version. This is likely the hardest part of this entire migration, ensuring that a non-`sameersbn/docker-gitlab` instance can be over-taken by this image (with the correct db name/user/pass). Once that is done, breathe a sigh of relief, the hard part is over.

From there, I'd suggest you grab each of the successive latest minor versions and do an upgrade into it.

- [8.7.6](https://github.com/sameersbn/docker-gitlab/releases/tag/8.7.6)
- [8.8.5](https://github.com/sameersbn/docker-gitlab/releases/tag/8.8.5-1)
- [8.9.6-1](https://github.com/sameersbn/docker-gitlab/releases/tag/8.9.6-1)
- [8.10.7](https://github.com/sameersbn/docker-gitlab/releases/tag/8.10.7)
- [8.11.7](https://github.com/sameersbn/docker-gitlab/releases/tag/8.11.7)
- [8.12.7](https://github.com/sameersbn/docker-gitlab/releases/tag/8.12.7)
- and finally, to the current [8.13.5](https://github.com/sameersbn/docker-gitlab/releases/tag/8.13.5)

The rationale for doing this many upgrades is that the database structure changes between minor versions. It's much easier to deal with data migration from one database structure to the next, without having to worry about migrating two or three versions old data into the current. If you think about upgrading to 8.13 all database structures from 8.12, 8.11, 8.10, 8.9, etc, it gets rather complicated. Since most users tend to be within a few minor releases or at most one major release away, it's generally not a big undertaking.

This comment is just a start, lots of things are glossed over, such as your ability to pull multiple non-Synology-provided images onto your server. Good luck.

**Comment by oxoocoffee** [comment]
Thank you for your reply. Just to let you kmow i contacted synology about gitlab and i was told right away that this is 3rd party package and thwy do not suport it at all. I was asked to contact developer. But i could not get if this GitLab itself or someone else making this package. It looks like it is NOT Synology. So this is why i did stumble onto this project hoping that it is package maintainer

**Comment by r2evans** [comment]
I don't know if Synology is using this repo; I couldn't find much info from their web page, so who knows. Bottom line: if they won't support you running their gitlab, then it's all on your shoulders. If you don't need to use their images, then I recommend you find a good repo and stick with it. Sounds like they've already dismissed your concerns about an app they allegedly provided.

**Comment by GJRTimmer** [comment]
I can help a little. Synology is not using this repository. The developer of the package is 'GitLab Inc.' so I guess you have to ask around on gitlab.org.

You are running a DS916+ can you tell me if you have the option to install docker through package center ? If you are able to run docker you can run this repository like I'm.
I'm running a full GitLab with docker repository and runners on my NAS.

If you can install docker, I can guide you in setting one up on a Synology.

If you don't have docker, then you probably have 5 choices.
1) Ask on gitlab.org who build the original and ask for an update
2) look for an updated version within a 3rd party repository
3) build the package your self, takes a little time to learn but not that hard
4) download the raw package file and update it to the latest version by replace some file within the spk file.
5) Buy a heavier Synology NAS which has docker support; ( My Favorite: 👍 ) 


PS. If you are interested, I've just completed writing a complete new gitlab-runner image, based upon sameersbn/gitlab-ci-multi-runner, this image also has branch specific for Synology. 
You can find it here: [https://hub.docker.com/r/datacore/gitlab-runner/] for the synology version look at the tags.

**Comment by oxoocoffee** [comment]
Thank you both for answering :)

I just did write email to GitLab asking them if they officially support GitLab on Synology or perhaps this package is made by someone else. I also did send email to Synology asking them for contact information about this 3rd party package.

GJRTimmer,

Thank you for your input. This might be very halpfull very soon if I do not hear for either above contact. My guess is I will hit dead end but I will try.

For your information I can install MariaDB and Docker with single click. The current versions are listed in my initial post above. Reading your post I see that my Docker can not be used with datacore/gitlab-runner:latest.  So unless I am missing something I might not be able to install it? Also do you have section about upgrading in future?

Thank you for your time

**Comment by GJRTimmer** [comment]
@oxoocoffee to my knowlegde Synology keeps all docker installs the same version, so you should be able to run docker from this repository.

If you need any help let me know. If no further help is required, please close this issue.

**Comment by oxoocoffee** [comment]
@GJRTimmer I will try to do your method sometimes this week and will post any challenges I encouter :)

**Comment by heximcz** [comment]
**Clear install and upgrade example:**
- delete default gitlab and redis container
- create ssl certificate over let's encrypt for gitlab.<your domain>.com in Synology
- connect to the Synology NAS over SSH:
- switch as root: sudo -i
- save following config to the:
```/volume1/docker/<my directory>/compose/gitlab/docker-compose.yml```
- create directories in /volume1 (your data will be here):
 - ```mkdir -p /volume1/docker/<my directory>/postgresql```
 - ```mkdir -p /volume1/docker/<my directory>/redis```
 - ```mkdir -p /volume1/docker/<my directory>/gitlab```
- (change configuration text in '<>')

```
version: '2'
services:
  redis:
    container_name: my_redis
    restart: always
    image: sameersbn/redis:latest
    command:
      - --loglevel warning
    volumes:
      - /volume1/docker/<my directory>/redis:/var/lib/redis

  postgresql:
    container_name: my_postgres
    restart: always
    image: sameersbn/postgresql:latest
    volumes:
      - /volume1/docker/<my directory>/postgresql:/var/lib/postgresql
    environment:
      - DB_USER=<db user>
      - DB_NAME=<db name>
      - DB_PASS=<password>
      - DB_EXTENSION=pg_trgm

  gitlab:
    container_name: my_gitlab
    image: 'sameersbn/gitlab:8.13.5'
    depends_on:
      - redis
      - postgresql
    hostname: 'gitlab.<your domain>.com'
    environment:
      - DEBUG=false

      - DB_ADAPTER=postgresql
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USER=<db user>
      - DB_NAME=<db name>
      - DB_PASS=<password>

      - REDIS_HOST=redis
      - REDIS_PORT=6379

      - TZ=Europe/Prague

      - GITLAB_TIMEZONE=Prague
      - GITLAB_PORT=10443
      - GITLAB_SSH_PORT=10022
      - GITLAB_HTTPS=true

      - GITLAB_SECRETS_DB_KEY_BASE=<random number>
      - GITLAB_SECRETS_SECRET_KEY_BASE=<random number>
      - GITLAB_SECRETS_OTP_KEY_BASE=<random number>

      - GITLAB_HOST=gitlab.<your domain>.com

      - GITLAB_BACKUP_SCHEDULE=daily
      - GITLAB_BACKUP_TIME=01:00

      - SMTP_ENABLED=true
      - SMTP_DOMAIN=gitlab.<your domain>.com
      - SMTP_HOST=<smtp host>
      - SMTP_PORT=587
      - SMTP_USER=<email>
      - SMTP_PASS=<password>
    ports:
      - '10022:22'
      - '10080:80'
      - '10443:443'
    external_links:
      - my_postgres:postgresql
      - my_redis:redisio
    volumes:
      - '/volume1/docker/<my directory>/gitlab:/home/git/data'
```

run docker compose:
```
docker-compose -f /volume1/docker/<my directory>/compose/gitlab/docker-compose.yml up -d
```

check if containers is running:
```
docker-compose -f /volume1/docker/<my directory>/compose/gitlab/docker-compose.yml ps
```

stop:
```
docker-compose -f /volume1/docker/<my directory>/compose/gitlab/docker-compose.yml stop
```

**Upgrade:**

- stop container: ```docker-compose -f /volume1/docker/<my directory>/compose/gitlab/docker-compose.yml stop```
- edit docker-compose.yml and change ```image: 'sameersbn/gitlab:8.13.5'``` section to the last stable version
- remove containers: ```docker-compose -f /volume1/docker/hexim/compose/gitlab/docker-compose.yml rm --all```
- remove old images:
 - List all images: ```docker images```
 - Delete specific image: ```docker rmi <image ID>```

**Comment by oxoocoffee** [comment]
@heximcz Would you mind edit your post with MariaDB instead postgresql? I used MySQL for some time and that is what I have installed on DS. On different note is there some advantage of using postgresql vs MariaDB from your experience?

**Comment by heximcz** [comment]
I prefer default setting for GitLab (PostgreSQL) but you can try use MySQL:

```
version: '2'
services:
  redis:
    container_name: my_redis
    restart: always
    image: sameersbn/redis:latest
    command:
      - --loglevel warning
    volumes:
      - /volume1/docker/<my directory>/redis:/var/lib/redis

  gitlab:
    container_name: my_gitlab
    image: 'sameersbn/gitlab:8.13.5'
    depends_on:
      - redis
    hostname: 'gitlab.<your domain>.com'
    environment:
      - DEBUG=false

      - DB_ADAPTER=mysql2
      - DB_HOST=<IP ADDRESS or host>
      - DB_PORT=<port number>
      - DB_USER=<db user>
      - DB_NAME=<db name>
      - DB_PASS=<password>

      - REDIS_HOST=redis
      - REDIS_PORT=6379

      - TZ=Europe/Prague

      - GITLAB_TIMEZONE=Prague
      - GITLAB_PORT=10443
      - GITLAB_SSH_PORT=10022
      - GITLAB_HTTPS=true

      - GITLAB_SECRETS_DB_KEY_BASE=<random number>
      - GITLAB_SECRETS_SECRET_KEY_BASE=<random number>
      - GITLAB_SECRETS_OTP_KEY_BASE=<random number>

      - GITLAB_HOST=gitlab.<your domain>.com

      - GITLAB_BACKUP_SCHEDULE=daily
      - GITLAB_BACKUP_TIME=01:00

      - SMTP_ENABLED=true
      - SMTP_DOMAIN=gitlab.<your domain>.com
      - SMTP_HOST=<smtp host>
      - SMTP_PORT=587
      - SMTP_USER=<email>
      - SMTP_PASS=<password>
    ports:
      - '10022:22'
      - '10080:80'
      - '10443:443'
    external_links:
      - my_redis:redisio
    volumes:
      - '/volume1/docker/<my directory>/gitlab:/home/git/data'
```

**Comment by GJRTimmer** [comment]
@oxoocoffee can you tell us the progress, and if all is ok, could you please close this issue ?

**Comment by oxoocoffee** [comment]
I am away for little over a week and have no access to unit. I will close it for now and try later. If I have issue I will reopen. 
Thank you

**Comment by kdesigns** [comment]
Any news yet?
