### ISSUE TITLE
All master branches are protected with upgrade to 8.14.1

### ISSUE THREAD

**Issue by adamlc** [sameersbn/docker-gitlab#995]
Not sure what's happened but after upgrading from 8.14.0 to 8.14.1 all the master branches in all repos have had their status changed to protected, maybe more bad migration or something? Anyone else had this issue? All other branches seem to be OK.

I know its not the end of the world because changing back to unprotected works fine, but thought I'd mention it 👍

**Comment by r2evans** [comment]
That is the default behavior for GitLab (src: [protected_branches.html](https://docs.gitlab.com/ce/user/project/protected_branches.html#configuring-protected-branches)). I don't know when it became default, since a [commit on July 22](https://gitlab.com/gitlab-org/gitlab-ce/commit/1a5b7e7d70cfe4802e858f129779e388307fbbab#ce29b2e1034f54526853bdd8fb7cdc4e3f2757d8) implies the verbiage (on line 13 of the old version) was already there at that time.

I'm still on `sameersbn/gitlab:8.14.0` and my `master` branches are all protected (and I've done nothing to set or change them).

I'm not saying this is not an issue. If you had previously *un*protected all of your `master` branches, or the branches were created before this became the default mode in GitLab, then who knows.

If that's the case, then it's likely something for [GitLab issues](https://gitlab.com/gitlab-org/gitlab-ce/issues/), not here, since I believe this docker image is not doing anything *that specific* to repos.

**Comment by gilyes** [comment]
I upgraded as well from 8.14.0 to 8.14.1, and now I can't push to my protected branches that I could push to before. Getting error saying "`remote: GitLab: You are not allowed to force push code to a protected branch on this project`" even though I am not force pushing. But yeah, most likely this is an issue for GitLab.

**Comment by r2evans** [comment]
Users belonging to the "Masters" list can push to the `master` branch. I think only the repo owner (since it is a per-repo setting) can change this, but perhaps other "Masters" can do it as well.

To find the list, within the repo pull down the "repo gear" (top-right corner, typically under the user avatar) and select "Members". Each member that has been granted access will be specifically listed as a "Master" (among "Guest", "Reporter", "Developer", and "Master"). If instead of "Members" you go to "Protected Branches", the level required to push can be set. "Merge" ops can be "Masters" or "Masters+Developers", while "Push" ops can be restricted to "Masters", "Master+Developers", or "No one".

Odd that the behavior appears to be have modified from what was there before. Are you certain it changed at exactly the transition from 8.14.0 to 8.14.1? (Not that your answer here will affect my ability to help, but it might be useful if/when you take it to GitLab Issues.)

**Comment by gilyes** [comment]
Yes, the issue started immediately after upgrading to 8.14.1. I am the Owner on those repos and tried all combinations with no success. If I take off branch protection all is good. Given the actual error message (talking about *force* push) if GitLab somehow thinks I am force pushing then it is expected to reject it. But I am not force pushing, Tried it from different machines, different repos, same result.

**Comment by r2evans** [comment]
I'm stumped, sorry. (And GitLab is a bit swamped, you may not get much from them.) I suggest going to GitLab Issues as well as posting to ServerFault and/or StackOverflow (for community response).

**Comment by gilyes** [comment]
Yeah, I might do that thanks.

**Comment by gilyes** [comment]
According to [this](https://gitlab.com/gitlab-org/gitlab-ce/issues/21502#note_19401533) comment the issue preventing regular push to protected branches may be caused by a change in behavior between Git versions. 

Essentially, the output of a git command in a specific scenario apparently changed from empty to a non-empty string, causing GitLab to erroneously think that a regular push is forced push. 

The commenter reverted the GitLab container's Git version from 2.11 to 1.9.1 and the issue disappeared.

**Comment by evenh** [comment]
I'm seeing this issue as well. Let's hope it is resolved quickly upstream.

**Comment by thomasf** [comment]
The defaults for protection has been like that for a long time, I now see these errors after upgrading to 8.14:

https://gitlab.com/gitlab-org/gitlab-ce/issues/25301#note_19420235

**Comment by adamlc** [comment]
Ahh didn't realise that was the default behaviour, but I guess this bug in git bought it to my attention. I'm not sure what implications downgrading git would have in the container. Its probably worth waiting for an upstream fix I'd say.

**Comment by jasl8r** [comment]
FYI, you can release a quick patch by installing an older version of git still available on the Ubuntu servers:

`apt get install -y git=1:1.9.1-1ubuntu0.3 git-man=1:1.9.1-1ubuntu0.3`

**Comment by Klowner** [comment]
Seeing the same issue on the published 8.14.4 image still. Can't push to `master` even though it's a regular push (non-forced) and I'm a project "Master".

**Comment by galet** [comment]
@jasl8r, is downgrading to 1.9.1 a safe workaround? GitLab says the minimal compatible Git version is 2.8.

**Comment by solidnerd** [comment]
I would recommend to downgrade to a version like `2.10.2` Currently I don't know where you can get  from the ubuntu space. I look into it in the evening.

**Comment by jasl8r** [comment]
I believe 1.9.1 is fine for now.  According to [this discussion](https://gitlab.com/gitlab-org/gitlab-ce/issues/14758) the main reason for the requirement is due to security issues that have been backported in the Ubuntu release.  It looks like 2.7+ is required to render the 'deployed at' text, but it appears that just falls back to a basic 'deployed to environment' link instead.

Alternatively you can just compile git from source...

**Comment by lyda** [comment]
Sorry @solidnerd, I looked but didn't see this.

I'm trying to make a fix.  The other version in Ubuntu 14.04 is 1.9.1 which is too old. Gitlab wants git version 2.8.4.

The git maintainers [ppa](https://launchpad.net/~git-core/+archive/ubuntu/ppa) won't work as it only has 2.11.0, 2.4.6 and 2.3.7.

**Comment by lyda** [comment]
Testing a fix now. Pull request soon.

**Comment by lyda** [comment]
Note that I've gotten this to build, but have not yet deployed to see if it fixes the issue. For dumb reasons this will require me to build it a second time and the deploy it. Which will take a while. However I think it should address the issue.

**Comment by r2evans** [comment]
@lyda, nice, thanks for going that route. Do you know if the *client* version of `git` (not within the GitLab environment) impacts the issue, or is it just the `git` that GitLab uses internally?

**Comment by lyda** [comment]
The version git uses internally causes the issue. I was seeing the issue
with git 2.9.3 on my laptop, but just from reading the bug it's clear that
it's being cause on the server (gitlab) side. I'll try and fix it on the
gitlab side tomorrow.

Kevin

**Comment by r2evans** [comment]
@lyda, looks like your temporary patch will be much needed, as the [upstream fix](https://gitlab.com/gitlab-org/gitlab-ce/issues/25301) may be taking a bit more work to accept. (But they do "confirm" the problem is the internal `git-2.11`, and downgrading to `git-2.10.2` appears to temporarily fix the symptom.)

**Comment by liangsuilong** [comment]
The upstream has fixed the issue on Gitlab 8.15. [https://gitlab.com/gitlab-org/gitlab-ce/issues/25301](https://gitlab.com/gitlab-org/gitlab-ce/issues/25301)

I think we could follow the upstream version to deal with this problem.

**Comment by solidnerd** [comment]
I updated gitlab to 8.15+ so for me this problem doesn't exist anymore. Can anyone upgrade his system and say if it works ?

**Comment by marcwrobel** [comment]
@solidnerd, I just tested and the problem has been fixed by the upgrade to 8.15.0.

**Comment by Fullm3tal** [comment]
After update to 8.15.1, I confirm also that the issue is fixed.

**Comment by evenh** [comment]
I can confirm that upgrading to 8.15.1 fixes the problem here as well.

**Comment by QuickJack** [comment]
There's another thread on the issue https://gitlab.com/gitlab-com/support-forum/issues/207

**Comment by lyda** [comment]
Fixes it for me, closing my PR.

**Comment by adamlc** [comment]
Sorry I didn't get back sooner, the upgrade resolves the issue, thanks 👍
